; Script generated by Terabithia Sync Build Pipeline
; Inno Setup 6.x Script for Terabithia Sync

#define MyAppName "Terabithia Sync"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Yunus İNAN"
#define MyAppCopyright "© Yunus İNAN - Tüm Hakları Saklıdır."
#define MyAppExeName "TerabithiaSync.exe"
#define MyAppIcon "app_icon.ico"
#define MyLicenseFile "..\LICENSE.txt"
#define SourcePublishDir "..\ScheduledCopyManager.App\bin\Release\net8.0-windows10.0.17763.0\win-x64\publish"

[Setup]
AppId={{D8F9A4E2-5678-4321-9ABC-FEDCBA987654}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppCopyright={#MyAppCopyright}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile={#MyLicenseFile}
SetupIconFile={#MyAppIcon}
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
OutputDir=..\InstallerOutput
OutputBaseFilename=TerabithiaSync-Setup-1.0.0
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#SourcePublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
